### ISSUE TITLE
feat: Upload artifacts 部分减少无用部分

### ISSUE THREAD

**Issue by sti-233** [BnqDzj/BiliRoamingX-PreBuilds#1]
## 主要问题
Github Action 显示上传的文件接近500MiB
可实际上BiliBili原包仅约150MiB
这额外的部分实际上并没有用

## 功能简述
仅上传patch后的BiliBili

## 实现逻辑
由于patch输出的BiliBili名称固定为
`${{ input_file_name }}-patched.apk`
于是可以指定上传这个文件

## 实现参考
更改"BiliRoamingX-PreBuilds.yml"的构建部分如下
```
      - name: Run ReVanced CLI
        run: |
          cd /Downloads/
          java -jar /Downloads/revanced-cli.jar patch --merge /Downloads/integrations.apk --patch-bundle /Downloads/patches.jar --signing-levels 1,2,3 /Downloads/BiliBili.apk

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: BiliRoamingX PreBuilds
          path: /Downloads/BiliBili-patched.apk
```
